import {BalanceRow,Calculation,CalculationResult,MonthValues,months,Reservoir} from './whb';
export const emptyMonths=():MonthValues=>Array(12).fill(0);
export const sum=(v:number[])=>v.reduce((a,b)=>a+(Number(b)||0),0);
export function flowToVolume(flowM3s:number,monthIndex:number,year:number){const days=new Date(year,monthIndex+1,0).getDate();return flowM3s*days*24*3600/1_000_000;}
export function normalizeRowValues(row:BalanceRow,year:number){return row.unit==='м³/с'?row.values.map((v,i)=>flowToVolume(v,i,year)):row.values.map(v=>Number(v)||0)}
export function distributeAnnual(total:number,mode:'Равномерно'|'Коэффициенты'|'Сезонный профиль',coeff?:number[]){if(mode==='Равномерно')return Array(12).fill(total/12);const c=coeff?.length===12?coeff:Array(12).fill(1);const s=sum(c)||1;return c.map(x=>total*x/s)}
export function calculateReservoir(r:Reservoir){const end:number[]=[];const warnings:string[]=[];for(let i=0;i<12;i++){const start=i===0?(r.start[0]||0):end[i-1];let e=start+(r.inflow[i]||0)-(r.withdrawal[i]||0)-(r.release[i]||0)-(r.evaporation[i]||0)-(r.filtration[i]||0);if(e<r.deadVolume){warnings.push(`${r.name}: ${months[i]} — объем ниже мертвого объема.`);e=r.deadVolume}if(e>r.fullVolume){warnings.push(`${r.name}: ${months[i]} — объем выше полного объема.`);e=r.fullVolume}if(e<r.minVolume)warnings.push(`${r.name}: ${months[i]} — ниже минимального допустимого объема.`);if(e>r.maxVolume)warnings.push(`${r.name}: ${months[i]} — выше максимального допустимого объема.`);end.push(e)}return{...r,end,warnings}}
export function calculateBalance(calc:Calculation):CalculationResult{const inflowRows=calc.rows.filter(r=>r.kind==='inflow');const outflowRows=calc.rows.filter(r=>r.kind==='outflow');const warnings:string[]=[];const monthly=months.map((m,i)=>{const inflow=sum(inflowRows.map(r=>normalizeRowValues(r,calc.year)[i]));const requested=outflowRows.map(r=>normalizeRowValues(r,calc.year)[i]);const outflow=sum(requested);const balance=inflow-outflow;const freeFlow=Math.max(balance,0);const deficit=Math.max(outflow-inflow,0);let remaining=inflow;let actualOut=0;[...outflowRows].sort((a,b)=>(a.priority??99)-(b.priority??99)).forEach((r,idx)=>{const need=requested[outflowRows.indexOf(r)]||0;const supply=Math.min(need,Math.max(remaining,0));remaining-=supply;actualOut+=supply;if(need>supply) warnings.push(`${m}: дефицит по статье «${r.name}» ${(need-supply).toFixed(3)} млн м³.`)});const residualFlow=Math.max(remaining,0);const mismatch=inflow-actualOut-residualFlow;const provision=outflow>0?actualOut/outflow*100:100;return{month:m,inflow,outflow,balance,freeFlow,deficit,accountedOutflow:actualOut,residualFlow,mismatch,provision}});const annual={inflow:sum(monthly.map(x=>x.inflow)),outflow:sum(monthly.map(x=>x.outflow)),balance:sum(monthly.map(x=>x.balance)),freeFlow:sum(monthly.map(x=>x.freeFlow)),deficit:sum(monthly.map(x=>x.deficit)),accountedOutflow:sum(monthly.map(x=>x.accountedOutflow)),residualFlow:sum(monthly.map(x=>x.residualFlow)),mismatch:sum(monthly.map(x=>x.mismatch)),provision:sum(monthly.map(x=>x.accountedOutflow))/Math.max(sum(monthly.map(x=>x.outflow)),0.000001)*100};return{monthly,annual,downstreamTransfer:monthly.map(x=>x.freeFlow),warnings}}
export function updateDownstream(calcs:Calculation[],vhOrder:string[]){return calcs.map(c=>({...c,rows:c.rows.map(r=>({...r,values:[...r.values]}))})).sort((a,b)=>vhOrder.indexOf(a.selectedVhuId)-vhOrder.indexOf(b.selectedVhuId));}
